CREATE TABLE IF NOT EXISTS TB_RECORD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICE VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    SCHEDULING_DATE DATE NOT NULL DEFAULT CURRENT_DATE
);