server:
  port: 8081
spring:
  application:
    name: planner-api
  datasource:
    url: jdbc:mariadb://localhost:3306/planner
    username: planner
    password: planner
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    url: jdbc:mariadb://localhost:3306/planner
    user: planner
    password: planner